"""remove_client_agency_referred_id

Revision ID: 1fac88bbbe70
Revises: 20260215_redesign
Create Date: 2026-03-05 15:25:06.291924

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1fac88bbbe70"
down_revision = "20260215_redesign"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simple_entities")
    op.drop_table("entities")
    op.drop_index("ix_admins_email", table_name="admins")
    op.drop_index("ix_admins_supabase_user_id", table_name="admins")
    op.create_unique_constraint(None, "admins", ["supabase_user_id"])
    op.create_unique_constraint(None, "admins", ["email"])
    op.drop_index("ix_agencies_email", table_name="agencies")
    op.create_unique_constraint(None, "agencies", ["email"])
    op.drop_index("ix_agents_supabase_user_id", table_name="agents")
    op.create_unique_constraint(None, "agents", ["supabase_user_id"])
    op.drop_index("ix_clients_email", table_name="clients")
    op.drop_constraint("clients_agency_referred_id_fkey", "clients", type_="foreignkey")
    op.drop_column("clients", "agency_referred_id")
    op.drop_index("ix_donors_email", table_name="donors")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_donors_email", "donors", ["email"], unique=True)
    op.add_column(
        "clients",
        sa.Column(
            "agency_referred_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "clients_agency_referred_id_fkey",
        "clients",
        "agencies",
        ["agency_referred_id"],
        ["id"],
    )
    op.create_index("ix_clients_email", "clients", ["email"], unique=True)
    op.drop_constraint(None, "agents", type_="unique")
    op.create_index(
        "ix_agents_supabase_user_id", "agents", ["supabase_user_id"], unique=True
    )
    op.drop_constraint(None, "agencies", type_="unique")
    op.create_index("ix_agencies_email", "agencies", ["email"], unique=True)
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_constraint(None, "admins", type_="unique")
    op.create_index(
        "ix_admins_supabase_user_id", "admins", ["supabase_user_id"], unique=True
    )
    op.create_index("ix_admins_email", "admins", ["email"], unique=True)
    op.create_table(
        "entities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("string_field", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("int_field", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "enum_field",
            postgresql.ENUM("A", "B", "C", "D", name="enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "string_array_field",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bool_field", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="entities_pkey"),
    )
    op.create_table(
        "simple_entities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("string_field", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("int_field", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "enum_field",
            postgresql.ENUM("A", "B", "C", "D", name="simple_entity_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "string_array_field",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bool_field", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="simple_entities_pkey"),
    )
    # ### end Alembic commands ###
