"""initial

Revision ID: 2adf14c14d9c
Revises:
Create Date: 2026-02-15 21:51:12.751263

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2adf14c14d9c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string_field", sa.String(), nullable=False),
        sa.Column("int_field", sa.Integer(), nullable=False),
        sa.Column(
            "enum_field", sa.Enum("A", "B", "C", "D", name="enum"), nullable=False
        ),
        sa.Column("string_array_field", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("bool_field", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simple_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string_field", sa.String(), nullable=False),
        sa.Column("int_field", sa.Integer(), nullable=False),
        sa.Column(
            "enum_field",
            sa.Enum("A", "B", "C", "D", name="simple_entity_enum"),
            nullable=False,
        ),
        sa.Column("string_array_field", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("bool_field", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simple_entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
