"""rename_furniture_dispatch_id_to_route_id

Revision ID: 2f907bea2c75
Revises: 1fac88bbbe70
Create Date: 2026-03-09 02:50:01.205536

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2f907bea2c75"
down_revision = "1fac88bbbe70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "furniture", sa.Column("route_id", sa.String(length=36), nullable=True)
    )
    op.drop_constraint("furniture_dispatch_id_fkey", "furniture", type_="foreignkey")
    op.create_foreign_key(None, "furniture", "routes", ["route_id"], ["id"])
    op.drop_column("furniture", "dispatch_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "furniture",
        sa.Column(
            "dispatch_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "furniture", type_="foreignkey")
    op.create_foreign_key(
        "furniture_dispatch_id_fkey", "furniture", "routes", ["dispatch_id"], ["id"]
    )
    op.drop_column("furniture", "route_id")
    # ### end Alembic commands ###
